name: schedule_app
description: "Schedule"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.3+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  file_picker: ^5.2.1
  path_provider: ^2.0.16
  shared_preferences: ^2.2.3
  animated_bottom_navigation_bar: ^1.3.3
  package_info_plus: ^8.0.0
  flutter_native_splash: ^2.4.0
  icons_launcher: ^2.1.7
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/app/pattern.png
  - assets/app/logo.png
  - assets/app/splash_logo.png
  - assets/app/rounded_logo.png


flutter_native_splash:
  color: "#83D0CB"
  background_image: "assets/app/pattern.png"
  android: true
  ios: true
  android_12:
    image: assets/app/splash_logo.png


icons_launcher:
  image_path: "assets/app/logo.png"
  platforms:
    android:
      enable: true
      adaptive_round_image: "assets/app/rounded_logo.png"
    ios:
      enable: true

